### ISSUE TITLE
info command broken

### ISSUE THREAD

**Issue by tauheed25** [sarfraznawaz2005/quran-cli#2]
## environment:
- npm version 6.4.1
- macos Mojave 

## problem:
When trying to get information of chapter an error is thrown:

```

quran info 12
events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'index' of undefined
    at getChapterInfo (/Users/tahmed/tools/quran-cli/app.js:82:30)
    at readData (/Users/tahmed/tools/quran-cli/app.js:25:20)
    at /Users/tahmed/tools/quran-cli/app.js:210:29
    at Parser.<anonymous> (/Users/tahmed/tools/quran-cli/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/Users/tahmed/tools/quran-cli/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/tahmed/tools/quran-cli/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/tahmed/tools/quran-cli/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/tahmed/tools/quran-cli/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/tahmed/tools/quran-cli/node_modules/sax/lib/sax.js:1436:13)
Emitted 'error' event at:
    at Parser.exports.Parser.Parser.parseString (/Users/tahmed/tools/quran-cli/node_modules/xml2js/lib/parser.js:326:16)
    at Parser.parseString (/Users/tahmed/tools/quran-cli/node_modules/xml2js/lib/parser.js:5:59)
    at /Users/tahmed/tools/quran-cli/app.js:206:32
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by sarfraznawaz2005** [comment]
Thanks for pointing out, i have fixed it now. Thanks
